### ISSUE TITLE
firstDigit does not work single digits.

### ISSUE THREAD

**Issue by PatheticMustan** [00100000spacebar/mathmethods#1]
https://github.com/00100000spacebar/mathmethods/blob/08fad307a8ee8cdc21ab802e7a8b5ac54156eaf8/Methods.java#L56

Let's test the input `5`. The result should be `5`.
```
do {
    n /= 10;
} while (n >= 10);
return n;
```

n is equal to 5
`n /= 10` n is equal to 0
`} while (n >= 10);` n is less than 10, the function ends.
`return n;` n is 0, so returns 0.
``

**Comment by 00100000spacebar** [comment]
my bad, I'll work on  it

**Comment by 00100000spacebar** [comment]
why do I keep closing issues lol

**Comment by 00100000spacebar** [comment]
fixed
