### ISSUE TITLE
allDigitsOdd only checks if the last digit is odd.

### ISSUE THREAD

**Issue by PatheticMustan** [00100000spacebar/mathmethods#2]
https://github.com/00100000spacebar/mathmethods/blob/08fad307a8ee8cdc21ab802e7a8b5ac54156eaf8/Methods.java#L62

```java
int divByTen = (n % 10) % 2;
if (divByTen != 0) {
    return true;
} else {
    return false;
}
```

this will only check if the first number is odd, which is not what is required of the function.

**Comment by 00100000spacebar** [comment]
Fixed with a loop. Thanks Mustan.
