### ISSUE TITLE
allDigitsSame does not work???

### ISSUE THREAD

**Issue by PatheticMustan** [00100000spacebar/mathmethods#3]
https://github.com/00100000spacebar/mathmethods/blob/08fad307a8ee8cdc21ab802e7a8b5ac54156eaf8/Methods.java#L71-L90

Lines 74-76 will return true if the last digit is odd?

```java
while (n > 0) {
    int modTenModTwo = n % 10;
    if (modTenModTwo % 2 == 0)
        evenNess++;
    else
        return false;
    n /= 10;
}
```
Lines 77-84 loop through each digit in the number.
It looks like you're saying if the current digit is even, you'll add one to `evenNess`. Otherwise, if the current digit is false, you return false for the whole function???

```java
if (evenNess == n) {
    return false;
} else {
    return true;
}
```
Lines 85-89 are saying that if the number of even digits in the number are equal to the number, the digits are not all even. Otherwise, all the digits are even.

I'm not sure what you're trying to do, but you need to fix literally everything in your program.

**Comment by 00100000spacebar** [comment]
fixed now
