### ISSUE TITLE
hasMidpoint(3, 3, 4) should return false.

### ISSUE THREAD

**Issue by PatheticMustan** [00100000spacebar/mathmethods#5]
`This method takes three integers as parameters and returns true if the average of any two of them is the third.`
One of the ways you can calculate this is using the equation
`(a + b) / 2 == c`.

Currently, using your program, `hasMidpoint(3, 3, 4)` returns `true`.

(3 + 4) / 2 != 3
(3 + 3) / 2 != 4
(4 + 3) / 2 != 3

HINT: Look at the difference between `int` and `double`.

**Comment by 00100000spacebar** [comment]
I know the difference between int and double, but I don't think she wants us to convert it to double if she gave us integers.

**Comment by PatheticMustan** [comment]
Not what I meant. What I'm saying is, hasMidpoint doesn't work with the case (3,3,4), which should be false, but returns true.

What I meant was BECAUSE you're dividing with integers, anything after the decimal point is lost.
